import { Component, OnInit } from '@angular/core';
import {FormArray, FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {CottageService} from '../service/cottage.service';
import {HttpClient} from '@angular/common/http';
import {Observable, OperatorFunction} from 'rxjs';
import {MatSnackBar} from '@angular/material/snack-bar';
import {ConfigService} from '../service/config.service';
import {UserService} from '../service/user.service';
import {CottageDTO} from '../model/cottage-dto.model';
import {EntityService} from '../service/entity.service';
import {debounceTime, distinctUntilChanged, map} from 'rxjs/operators';

// const cities = [
//   'Ada',
//   'Adaševci',
//   'Adorjan',
//   'Adrani',
//   'Azanja',
//   'Aleksa Šantić',
//   'Aleksandrovac',
//   'Aleksandrovac',
//   'Aleksandrovo',
//   'Aleksinac',
//   'Aleksinački Rudnik',
//   'Alibunar',
//   'Aljinovići',
//   'Apatin',
//   'Aradac',
//   'Aranđelovac',
//   'Arilje',
//   'Ašanja',
//   'Babušnica',
//   'Bavanište',
//   'Bagrdan',
//   'Badnjevac',
//   'Badovinci',
//   'Bajina Bašta',
//   'Bajmok',
//   'Bajša',
//   'Balajnac',
//   'Baljevac',
//   'Banatska Dubica',
//   'Banatska Palanka',
//   'Banatska Subotica',
//   'Banatska Topola',
//   'Banatski Brestovac',
//   'Banatski Dvor',
//   'Banatski Despotovac',
//   'Banatski Karlovac',
//   'Banatsko Aranđelovo',
//   'Banatsko Veliko Selo',
//   'Banatsko Karađorđevo',
//   'Banatsko Novo Selo',
//   'Banovo Polje',
//   'Banovci-Dunav',
//   'Banoštor',
//   'Banja',
//   'Banja (kod Priboja)',
//   'Banja Koviljača',
//   'Banjani',
//   'Banjska',
//   'Barajevo',
//   'Baranda',
//   'Barbatovac',
//   'Bare',
//   'Bare',
//   'Bare',
//   'Barice',
//   'Barič',
//   'Barlovo',
//   'Baroševac',
//   'Batočina',
//   'Batrovci',
//   'Batuse',
//   'Bač',
//   'Bačevci',
//   'Bačina',
//   'Bačinci',
//   'Bačka Palanka',
//   'Bačka Topola',
//   'Bački Breg',
//   'Bački Brestovac',
//   'Bački Vinogradi',
//   'Bački Gračac',
//   'Bački Jarak',
//   'Bački Monoštor',
//   'Bački Petrovac',
//   'Bački Sokolac',
//   'Bačko Gradište',
//   'Bačko Dobro Polje',
//   'Bačko Novo Selo',
//   'Bačko Petrovo Selo',
//   'Bašaid',
//   'Begeč',
//   'Bezdan',
//   'Bela Voda',
//   'Bela Zemlja',
//   'Bela Palanka',
//   'Bela Crkva',
//   'Bela Crkva',
//   'Belanovica',
//   'Bele Vode',
//   'Belegiš',
//   'Beli Potok',
//   'Beli Potok',
//   'Belo Blato',
//   'Beloljin',
//   'Belosavci',
//   'Belotinac',
//   'Beloševac',
//   'Belušić',
//   'Beljina',
//   'Beograd',
//   'Beočin',
//   'Berkasovo',
//   'Bečej',
//   'Bešenovo',
//   'Beška',
//   'Bigrenica',
//   'Bikić Do',
//   'Bikovo',
//   'Biljača',
//   'Bingula',
//   'Bioska',
//   'Bistar',
//   'Bistrica',
//   'Blaževo',
//   'Blace',
//   'Bobovo',
//   'Bogaraš',
//   'Bogatić',
//   'Bogovađa',
//   'Bogovina',
//   'Bogojevo',
//   'Bogojevce',
//   'Bogutovac',
//   'Bođani',
//   'Boževac',
//   'Božetići',
//   'Božica',
//   'Bojnik',
//   'Boka',
//   'Boljevac',
//   'Boljkovci',
//   'Bor',
//   'Borski Brestovac',
//   'Bosilegrad',
//   'Bosut',
//   'Botoš',
//   'Bočar',
//   'Bošnjane',
//   'Bošnjace',
//   'Bradarac',
//   'Braničevo',
//   'Brankovina',
//   'Bratljevo',
//   'Braćevac',
//   'Brvenik',
//   'Brgule',
//   'Brđani',
//   'Brežđe',
//   'Brezjak',
//   'Brezna',
//   'Brezova',
//   'Brezovica',
//   'Brekovo',
//   'Bresnica',
//   'Brestovac',
//   'Brestovačka Banja',
//   'Brza Palanka',
//   'Brzi Brod',
//   'Brzan',
//   'Brzeće',
//   'Brodarevo',
//   'Brus',
//   'Brusnik',
//   'Budisava',
//   'Buđanovci',
//   'Bujanovac',
//   'Bukovac',
//   'Bukovik',
//   'Bukovica',
//   'Bukorovac',
//   'Bunar',
//   'Burdimo',
//   'Burovac',
//   'Busilovac',
//   'Bučje',
//   'Vajska',
//   'Valjevo',
//   'Varvarin',
//   'Varda',
//   'Varna',
//   'Varoš',
//   'Vasilj',
//   'Vatin',
//   'Vašica',
//   'Velebit',
//   'Velesnica',
//   'Velika Vrbnica',
//   'Velika Grabovnica',
//   'Velika Greda',
//   'Velika Drenova',
//   'Velika Ivanča',
//   'Velika Jasikova',
//   'Velika Krsna',
//   'Velika Lomnica',
//   'Velika Moštanica',
//   'Velika Plana',
//   'Velika Plana',
//   'Velika Reka',
//   'Veliki Borak',
//   'Veliki Gaj',
//   'Veliki Izvor',
//   'Veliki Popović',
//   'Veliki Radinci',
//   'Veliki Trnovac',
//   'Veliki Crljeni',
//   'Veliki Šiljegovac',
//   'Veliko Bonjince',
//   'Veliko Gradište',
//   'Veliko Laole',
//   'Veliko Orašje',
//   'Veliko Središte',
//   'Venčane',
//   'Veternik',
//   'Vilovo',
//   'Vina',
//   'Vionica',
//   'Visočka Ržana',
//   'Vitanovac',
//   'Vitkovac',
//   'Vitoševac',
//   'Viča',
//   'Višnjevac',
//   'Višnjićevo',
//   'Vladimirovac',
//   'Vladimirci',
//   'Vladičin Han',
//   'Vlajkovac',
//   'Vlase',
//   'Vlasotince',
//   'Vlaška',
//   'Voganj',
//   'Vodanj',
//   'Vojvoda Stepa',
//   'Vojvodinci',
//   'Vojka',
//   'Vojska',
//   'Voluja',
//   'Vražogrnac',
//   'Vranić',
//   'Vranovo',
//   'Vranje',
//   'Vranjska Banja',
//   'Vratarnica',
//   'Vraćevšnica',
//   'Vračev Gaj',
//   'Vrba',
//   'Vrbas',
//   'Vrbica',
//   'Vrbovac',
//   'Vrdnik',
//   'Vreoci',
//   'Vrmdža',
//   'Vrnjačka Banja',
//   'Vrnjci',
//   'Vrćenovica',
//   'Vrhpolje',
//   'Vršac',
//   'Vukovac',
//   'Vučje',
//   'Gaj',
//   'Gajdobra',
//   'Gakovo',
//   'Gamzigradska Banja',
//   'Gardinovci',
//   'Gadžin Han',
//   'Gibarac',
//   'Glavinci',
//   'Globoder',
//   'Glogovac',
//   'Glogonj',
//   'Gložan',
//   'Glušci',
//   'Gnjilan',
//   'Golobok',
//   'Golubac',
//   'Golubinci',
//   'Goračići',
//   'Gornja Dobrinja',
//   'Gornja Draguša',
//   'Gornja Lisina',
//   'Gornja Sabanta',
//   'Gornja Toplica',
//   'Gornja Toponica',
//   'Gornja Trepča',
//   'Gornja Trnava',
//   'Gornje Dvorane',
//   'Gornji Barbeš',
//   'Gornji Breg',
//   'Gornji Matejevac',
//   'Gornji Milanovac',
//   'Gornji Stepoš',
//   'Gornji Stupanj',
//   'Gospođinci',
//   'Gostun',
//   'Grabovac',
//   'Grabovica',
//   'Grabovci',
//   'Gradskovo',
//   'Gračanica',
//   'Grgurevci',
//   'Grdelica',
//   'Grebenac',
//   'Grlište',
//   'Grljan',
//   'Grošnica',
//   'Gruža',
//   'Guberevac',
//   'Guberevac',
//   'Gudurica',
//   'Gunaroš',
//   'Guča',
//   'Guševac',
//   'Darosava',
//   'Debeljača',
//   'Debrc',
//   'Devojački Bunar',
//   'Deževa',
//   'Deliblato',
//   'Delimeđe',
//   'Deronje',
//   'Desimirovac',
//   'Despotovac',
//   'Despotovo',
//   'Deč',
//   'Divljaka',
//   'Divostin',
//   'Divoš',
//   'Divci',
//   'Divčibare',
//   'Dimitrovgrad',
//   'Dobra',
//   'Dobri Do',
//   'Dobrinci',
//   'Dobrić',
//   'Dobrica',
//   'Dolac',
//   'Dolovo',
//   'Doljevac',
//   'Donja Bela Reka',
//   'Donja Borina',
//   'Donja Gušterica',
//   'Donja Kamenica',
//   'Donja Ljubata',
//   'Donja Mutnica',
//   'Donja Orovica',
//   'Donja Rečica',
//   'Donja Trnava',
//   'Donja Šatornja',
//   'Donje Vidovo',
//   'Donje Zuniče',
//   'Donje Međurovo',
//   'Donje Crnatovo',
//   'Donje Crniljevo',
//   'Donji Dušnik',
//   'Donji Krčin',
//   'Donji Milanovac',
//   'Donji Stajevac',
//   'Doroslovo',
//   'Draginac',
//   'Draginje',
//   'Draglica',
//   'Dragobraća',
//   'Dragovo',
//   'Dragolj',
//   'Dragocvet',
//   'Dragoševac',
//   'Draževac',
//   'Draževac',
//   'Drajkovce',
//   'Dračić',
//   'Drenovac',
//   'Drenovac',
//   'Drugovac',
//   'Dublje',
//   'Dubovac',
//   'Dubovo',
//   'Duboka',
//   'Duboka',
//   'Dubočane',
//   'Dubravica',
//   'Duga Poljana',
//   'Dugo Polje',
//   'Dudovica',
//   'Dupljaja',
//   'Đala',
//   'Đunis',
//   'Đurđevo',
//   'Đurđin',
//   'Elemir',
//   'Erdevik',
//   'Erdeč',
//   'Ečka',
//   'Žabalj',
//   'Žabari',
//   'Žagubica',
//   'Željuše',
//   'Žirovnica',
//   'Žitište',
//   'Žitkovac',
//   'Žitni Potok',
//   'Žitorađa',
//   'Žiča',
//   'Žuč',
//   'Zablaće',
//   'Zabojnica',
//   'Zabrežje',
//   'Zavlaka',
//   'Zagajica',
//   'Zajača',
//   'Zaječar',
//   'Zaplanjska Toponica',
//   'Zasavica',
//   'Zvezdan',
//   'Zvečan',
//   'Zvonce',
//   'Zdravinje',
//   'Zlatibor',
//   'Zlatica',
//   'Zlodol',
//   'Zlot',
//   'Zmajevo',
//   'Zminjak',
//   'Zrenjanin',
//   'Zubin Potok',
//   'Zuce',
//   'Ivanovo',
//   'Ivanjica',
//   'Idvor',
//   'Iđoš',
//   'Izbište',
//   'Ilandža',
//   'Ilinci',
//   'Ilićevo',
//   'Inđija',
//   'Irig',
//   'Jabuka',
//   'Jabuka',
//   'Jabukovac',
//   'Jabučje',
//   'Jagnjilo',
//   'Jagodina',
//   'Jadranska Lešnica',
//   'Jazak',
//   'Jazovo',
//   'Jamena',
//   'Jankov Most',
//   'Janošik',
//   'Jarak',
//   'Jarkovac',
//   'Jarmenovci',
//   'Jasenovo',
//   'Jasenovo',
//   'Jasenovo',
//   'Jasika',
//   'Jasikovica',
//   'Jasikovo',
//   'Jaša Tomić',
//   'Ježevica',
//   'Ježevica',
//   'Jelašnica',
//   'Jelašnica',
//   'Jelen Do',
//   'Jelovik',
//   'Jermenovci',
//   'Jovanovac',
//   'Jovanovac',
//   'Jovac',
//   'Jošanica',
//   'Jošanička Banja',
//   'Jugbogdanovac',
//   'Junkovac',
//   'Kalna',
//   'Kaluđerica',
//   'Kamenica',
//   'Kamenica',
//   'Kamenica',
//   'Kanjiža',
//   'Kaona',
//   'Kaonik',
//   'Karavukovo',
//   'Karađorđevo',
//   'Karađorđevo',
//   'Karan',
//   'Karlovčić',
//   'Katun',
//   'Kać',
//   'Kačarevo',
//   'Kevi',
//   'Kelebija',
//   'Kelebija gran. prelaz',
//   'Kikinda',
//   'Kisač',
//   'Kladovo',
//   'Klek',
//   'Klenak',
//   'Klenike',
//   'Klenje',
//   'Klenje',
//   'Klisura',
//   'Kličevac',
//   'Klokočevac',
//   'Kljajićevo',
//   'Knić',
//   'Knićanin',
//   'Knjaževac',
//   'Kobišnica',
//   'Kovačevac',
//   'Kovačica',
//   'Kovilj',
//   'Kovin',
//   'Kokin Brod',
//   'Kolare',
//   'Kolari',
//   'Kolut',
//   'Komirić',
//   'Konak',
//   'Konarevo',
//   'Končarevo',
//   'Konjuh',
//   'Kopaonik',
//   'Koprivnica',
//   'Koraćica',
//   'Korbevac',
//   'Korbovo',
//   'Korenita',
//   'Korman',
//   'Korman',
//   'Kosančić',
//   'Kosjerić',
//   'Kosovo Polje',
//   'Kosovska Kamenica',
//   'Kosovska Mitrovica',
//   'Kostojevići',
//   'Kostolac',
//   'Kotraža',
//   'Koceljeva',
//   'Kragujevac',
//   'Krajišnik',
//   'Kraljevo',
//   'Kraljevci',
//   'Kremna',
//   'Krepoljin',
//   'Kriva Feja',
//   'Krivaja',
//   'Krivelj',
//   'Krivi Vir',
//   'Krnjevo',
//   'Krnješevci',
//   'Krupanj',
//   'Krupac',
//   'Krušar',
//   'Kruševac',
//   'Kruševica',
//   'Krušedol',
//   'Kruščić',
//   'Krčedin',
//   'Kuzmin',
//   'Kukljin',
//   'Kukujevci',
//   'Kula',
//   'Kulina',
//   'Kulpin',
//   'Kumane',
//   'Kupinik',
//   'Kupinovo',
//   'Kupusina',
//   'Kupci',
//   'Kuršumlija',
//   'Kuršumlijska Banja',
//   'Kusadak',
//   'Kusić',
//   'Kucura',
//   'Kučevo',
//   'Kušiljevo',
//   'Kušići',
//   'Kuštilj',
//   'Lađevci',
//   'Lazarevac',
//   'Lazarevo',
//   'Laznica',
//   'Lajkovac',
//   'Lalinac',
//   'Lalinac',
//   'Lalić',
//   'Laplje Selo',
//   'Lapovo',
//   'Lapovo (Varoš)',
//   'Laćarak',
//   'Lebane',
//   'Ledinci',
//   'Ležimir',
//   'Lelić',
//   'Lenovac',
//   'Lepenac',
//   'Lepenica',
//   'Lepina',
//   'Leposavić',
//   'Leskovac',
//   'Lece',
//   'Lešak',
//   'Lešnica',
//   'Lipar',
//   'Lipe',
//   'Lipnički Šor',
//   'Lipolist',
//   'Lički Hanovi',
//   'Lovćenac',
//   'Loznica',
//   'Lozovik',
//   'Lok',
//   'Lokve',
//   'Loćika',
//   'Lubnica',
//   'Lug',
//   'Lugavčina',
//   'Lužnice',
//   'Lukare',
//   'Lukino Selo',
//   'Lukićevo',
//   'Lukovo',
//   'Lukovska Banja',
//   'Lunovo Selo',
//   'Lučani',
//   'Ljig',
//   'Ljuba',
//   'Ljuberađa',
//   'Ljubiš',
//   'Ljubovija',
//   'Ljukovo',
//   'Ljutovo',
//   'Maglić',
//   'Majdan',
//   'Majdanpek',
//   'Majilovac',
//   'Majur',
//   'Majur',
//   'Mala Bosna',
//   'Mala Krsna',
//   'Mala Moštanica',
//   'Mala Plana',
//   'Male Pijace',
//   'Male Pčelice',
//   'Mali Beograd',
//   'Mali Zvornik',
//   'Mali Iđoš',
//   'Mali Izvor',
//   'Mali Jasenovac',
//   'Mali Požarevac',
//   'Malo Krčmare',
//   'Malo Crniće',
//   'Malošište',
//   'Malča',
//   'Manđelos',
//   'Manojlovce',
//   'Maradik',
//   'Margita',
//   'Markovac',
//   'Markovica',
//   'Martinci',
//   'Martonoš',
//   'Maršić',
//   'Mataruška Banja',
//   'Mačvanska Mitrovica',
//   'Mačvanski Pričinović',
//   'Mačkat',
//   'Medveđa',
//   'Medveđa',
//   'Medveđa',
//   'Medoševac',
//   'Međa',
//   'Međulužje',
//   'Međurečje',
//   'Melenci',
//   'Melenci-Rusanda',
//   'Meljak',
//   'Merdare',
//   'Merošina',
//   'Merćez',
//   'Metlić',
//   'Metovnica',
//   'Mijatovac',
//   'Milatovac',
//   'Milentija',
//   'Miletićevo',
//   'Mileševo',
//   'Miloševac',
//   'Miloševo',
//   'Milutovac',
//   'Minićevo',
//   'Mionica',
//   'Mirosaljci',
//   'Miroševce',
//   'Mitrovac',
//   'Mihajlovac',
//   'Mihajlovac',
//   'Mihajlovo',
//   'Mišićevo',
//   'Mladenovac',
//   'Mladenovo',
//   'Mozgovo',
//   'Mokra Gora',
//   'Mokrin',
//   'Mol',
//   'Molovin',
//   'Morović',
//   'Mošorin',
//   'Mramor',
//   'Mramorak',
//   'Mrčajevci',
//   'Mršinci',
//   'Mužlja',
//   'Muhovac',
//   'Nadalj',
//   'Nakovo',
//   'Natalinci',
//   'Negotin',
//   'Neresnica',
//   'Neuzina',
//   'Neštin',
//   'Nikinci',
//   'Nikolinci',
//   'Nikoličevo',
//   'Niš',
//   'Niševac',
//   'Niška Banja',
//   'Nova Varoš',
//   'Nova Gajdobra',
//   'Nova Pazova',
//   'Nova Crvenka',
//   'Nova Crnja',
//   'Novi Banovci',
//   'Novi Bečej',
//   'Novi Bračin',
//   'Novi Žednik',
//   'Novi Itebej',
//   'Novi Karlovci',
//   'Novi Kneževac',
//   'Novi Kozarci',
//   'Novi Kozjak',
//   'Novi Pazar',
//   'Novi Sad',
//   'Novi Slankamen',
//   'Novo Miloševo',
//   'Novo Orahovo',
//   'Novo Selo',
//   'Novo Selo',
//   'Noćaj',
//   'Obrež',
//   'Obrež',
//   'Obrenovac',
//   'Obrovac',
//   'Ovčar Banja',
//   'Ogar',
//   'Omoljica',
//   'Oparić',
//   'Opovo',
//   'Orane',
//   'Orašac',
//   'Oreškovica',
//   'Orid',
//   'Orlovat',
//   'Orom',
//   'Osanica',
//   'Osečina',
//   'Osipaonica',
//   'Ostojićevo',
//   'Ostrovica',
//   'Ostružnica',
//   'Odžaci',
//   'Oštrelj',
//   'Pavliš',
//   'Padež',
//   'Padej',
//   'Padina',
//   'Palić',
//   'Pambukovica',
//   'Panonija',
//   'Pančevo',
//   'Parage',
//   'Paraćin',
//   'Parteš',
//   'Parunovac',
//   'Pasjane',
//   'Pačir',
//   'Pejkovac',
//   'Pepeljevac',
//   'Perlez',
//   'Perućac',
//   'Petlovača',
//   'Petrovaradin',
//   'Petrovac',
//   'Pećinci',
//   'Pecka',
//   'Pečenjevce',
//   'Pivnice',
//   'Pinosava',
//   'Pirot',
//   'Plavna',
//   'Plavna',
//   'Plažane',
//   'Plana',
//   'Plandište',
//   'Platičevo',
//   'Plemetina',
//   'Pleš',
//   'Pločica',
//   'Pobeda',
//   'Poganovo',
//   'Podvis',
//   'Podvrška',
//   'Podgorac',
//   'Podunavci',
//   'Požarevac',
//   'Požega',
//   'Pojate',
//   'Poljana',
//   'Poljska Ržana',
//   'Popinci',
//   'Popovac',
//   'Popučke',
//   'Porodin',
//   'Potočac',
//   'Poćuta',
//   'Počekovina',
//   'Pranjani',
//   'Prahovo',
//   'Prevešt',
//   'Predejane',
//   'Prekonoga',
//   'Preljina',
//   'Preševo',
//   'Preševo-terminal',
//   'Priboj',
//   'Priboj Vranjski',
//   'Privina Glava',
//   'Prigrevica',
//   'Prijepolje',
//   'Prilički Kiseljak',
//   'Prilužje',
//   'Pričević',
//   'Prnjavor (Mačvanski)',
//   'Provo',
//   'Prokuplje',
//   'Prolom Banja',
//   'Pružatovac',
//   'Prhovo',
//   'Pukovac',
//   'Putinci',
//   'Rabrovo',
//   'Ravna Dubrava',
//   'Ravni Topolovac',
//   'Ravni',
//   'Ravno Selo',
//   'Ravnje',
//   'Radalj',
//   'Radinac',
//   'Radičević',
//   'Radljevo',
//   'Radovnica',
//   'Radojevo',
//   'Radujevac',
//   'Ražana',
//   'Ražanj',
//   'Razbojna',
//   'Razgojna',
//   'Rainovača',
//   'Rajković',
//   'Rakovac',
//   'Ralja',
//   'Ranilović',
//   'Ranilug',
//   'Ranovac',
//   'Rastina',
//   'Rataje',
//   'Ratari',
//   'Ratina',
//   'Ratkovo',
//   'Rača Kragujevačka',
//   'Rača',
//   'Rašanac',
//   'Raševica',
//   'Raška',
//   'Rgotina',
//   'Rekovac',
//   'Resavica',
//   'Resnik',
//   'Ribare',
//   'Ribari',
//   'Ribariće',
//   'Ribarska Banja',
//   'Riđica',
//   'Ripanj',
//   'Ristovac',
//   'Rogača',
//   'Rogačica',
//   'Roge',
//   'Rogljevo',
//   'Rožanstvo',
//   'Roćevići',
//   'Rudna Glava',
//   'Rudnik',
//   'Rudnica',
//   'Rudno',
//   'Rudovci',
//   'Ruma',
//   'Rumenka',
//   'Ruski Krstur',
//   'Rusko Selo',
//   'Rutevac',
//   'Rušanj',
//   'Savinac',
//   'Savino Selo',
//   'Sajan',
//   'Sakule',
//   'Salaš Noćajski',
//   'Salaš',
//   'Samaila',
//   'Samoš',
//   'Sanad',
//   'Saraorci',
//   'Sastav Reka',
//   'Sastavci',
//   'Sveti Ilija',
//   'Svetozar Miletić',
//   'Svilajnac',
//   'Svileuva',
//   'Svilojevo',
//   'Svođe',
//   'Svojnovo',
//   'Svrljig',
//   'Sevojno',
//   'Sedlare',
//   'Selevac',
//   'Selenča',
//   'Seleuš',
//   'Senta',
//   'Senje',
//   'Senjski Rudnik',
//   'Sefkerin',
//   'Seča Reka',
//   'Sečanica',
//   'Sečanj',
//   'Sibač',
//   'Sivac',
//   'Sijarinska Banja',
//   'Sikirica',
//   'Sikole',
//   'Silbaš',
//   'Siokovac',
//   'Sip',
//   'Sipić',
//   'Sirig',
//   'Sirogojno',
//   'Sirča',
//   'Sićevo',
//   'Sjenica',
//   'Skela',
//   'Skobalj',
//   'Skorenovac',
//   'Slavkovica',
//   'Slatina',
//   'Slovac',
//   'Smederevska Palanka',
//   'Smederevo',
//   'Smilovci',
//   'Smoljinac',
//   'Sokobanja',
//   'Sombor',
//   'Sonta',
//   'Sopot',
//   'Sot',
//   'Sočanica',
//   'Sremska Mitrovica',
//   'Srbobran',
//   'Srednjevo',
//   'Sremska Kamenica',
//   'Sremska Rača',
//   'Sremski Karlovci',
//   'Sremski Mihaljevci',
//   'Sremčica',
//   'Srpska Crnja',
//   'Srpski Itebej',
//   'Srpski Krstur',
//   'Srpski Miletić',
//   'Stave',
//   'Stajićevo',
//   'Stalać',
//   'Stanišić',
//
//   'Stapar',
//   'Stara Moravica',
//   'Stara Pazova',
//   'Stari Banovci',
//   'Stari Žednik',
//   'Stari Lec',
//   'Stari Slankamen',
//   'Staro Selo',
//   'Starčevo',
//   'Stejanovci',
//   'Stenjevac',
//   'Stepanovićevo',
//   'Stepojevac',
//   'Stojnik',
//   'Stopanja',
//   'Stragari',
//   'Straža',
//   'Strelac',
//   'Stubal',
//   'Stubica',
//   'Stubline',
//   'Studenica',
//   'Subotinac',
//   'Subotica (kod Svijanca)',
//   'Subotica',
//   'Subotište',
//   'Sukovo',
//   'Sumrakovac',
//   'Supska',
//   'Surduk',
//   'Surdulica',
//   'Susek',
//   'Sutjeska',
//   'Tavankut',
//   'Takovo',
//   'Taraš',
//   'Tekeriš',
//   'Tekija',
//   'Telečka',
//   'Temerin',
//   'Temska',
//   'Tešica',
//   'Titel',
//   'Toba',
//   'Tovariševo',
//   'Tomaševac',
//   'Tomislavci',
//   'Topola',
//   'Topolovnik',
//   'Toponica',
//   'Torak',
//   'Torda',
//   'Tornjoš',
//   'Totovo Selo',
//   'Trbušani',
//   'Trgovište',
//   'Trešnjevac',
//   'Trešnjevica',
//   'Trnavci',
//   'Trnjane',
//   'Trnjane',
//   'Trstenik',
//   'Trupale',
//   'Tršić',
//   'Tulare',
//   'Turekovac',
//   'Turija',
//   'Turija',
//   'Tutin',
//   'Ćićevac',
//   'Ćuprija',
//   'Ub',
//   'Ugao',
//   'Ugrinovci',
//   'Užice',
//   'Uzdin',
//   'Uzovnica',
//   'Uljma',
//   'Umka',
//   'Urovica',
//   'Utrine',
//   'Ušće',
//   'Farkaždin',
//   'Feketić',
//   'Futog',
//   'Hajdukovo',
//   'Hajdučica',
//   'Hetin',
//   'Horgoš',
//   'Horgoš granični prelaz',
//   'Hrtkovci',
//   'Cerovac',
//   'Crvena Reka',
//   'Crvena Crkva',
//   'Crvenka',
//   'Crepaja',
//   'Crkvine',
//   'Crna Bara',
//   'Crna Bara',
//   'Crna Trava',
//   'Crnoklište',
//   'Čajetina',
//   'Čalma',
//   'Čantavir',
//   'Čačak',
//   'Čelarevo',
//   'Čenej',
//   'Čenta',
//   'Čerević',
//   'Čestereg',
//   'Čečina',
//   'Čitluk',
//   'Čitluk',
//   'Čoka',
//   'Čonoplja',
//   'Čortanovci',
//   'Čukojevac',
//   'Čumić',
//   'Čurug',
//   'Džep',
//   'Džigolj',
//   'Šabac',
//   'Šajkaš',
//   'Šarbanovac',
//   'Šarbanovac-Timok',
//   'Šašinci',
//   'Šepšin',
//   'Šetonje',
//   'Šid',
//   'Šilovo',
//   'Šimanovci',
//   'Šljivovac',
//   'Šljivovica',
//   'Šljivovo',
//   'Štavalj',
//   'Štitar',
//   'Štitare',
//   'Štrpce',
//   'Štubik',
//   'Šupljak',
//   'Šurjan',
//   'Grocka',
//   'Surčin',
//   'Batajnica',
//   'Savski venac',
//   'Stari grad',
//   'Vračaar',
//   'Voždovac',
//   'Čukarica',
//   'Zvezdara',
//   'Palilula',
//   'Novi Beograd',
//   'Zemun',
//   'Rakovica'
// ];
@Component({
  selector: 'app-register-cottage',
  templateUrl: './register-cottage.component.html',
  styleUrls: ['./register-cottage.component.css']
})
export class RegisterCottageComponent implements OnInit {
  cottageCreationForm!: FormGroup;
  private selectedFile!: File;
  // tslint:disable-next-line:variable-name
  private _rooms!: FormArray;

  constructor(
    private formBuilder: FormBuilder,
    private http: HttpClient,
    private snackbar: MatSnackBar,
    private config: ConfigService,
    private userService: UserService,
    private entityService: EntityService
  ) {
  }
  cottage: CottageDTO = new CottageDTO();
  ngOnInit(): void {
    this.initializeForm();
  }

  onSubmit(): void {
    this.cottage = this.cottageCreationForm.getRawValue();
    this.cottage.reservations = [];
    this.cottage.cottageOwnerId = this.userService.currentUser.id;
    this.http.post<any>(this.config.cottages_url, this.cottage)
      .subscribe(res => {
        console.log(res.id);
        this.uploadImage(res.id);
      });
    this.approvedSnackBar();
  }
  // tslint:disable-next-line:typedef
  approvedSnackBar(): void{
    this.snackbar.open('Cottage is created', 'cancel')._dismissAfter(10);
  }
  public onFileChanged(event: any): void {
    this.selectedFile = event.target.files[0];
  }
  private uploadImage(id: number): void{
    const data: FormData = new FormData();
    data.append('imageUrl', this.selectedFile, this.selectedFile.name);
    this.entityService.saveEntityPhoto(data, id).subscribe(res => {console.log(res); });
  }
  createRooms(): FormGroup {
    return this.formBuilder.group({
      numberOfBeds: new FormControl(0)
    });
  }
  get getRooms(): FormArray {
    return this.cottageCreationForm.get('rooms') as FormArray;
  }
  addRoom(): void{
    this._rooms = this.cottageCreationForm.get('rooms') as FormArray;
    this._rooms.push(this.createRooms());
  }
  deleteRoom(index: number): void {
    this._rooms = this.cottageCreationForm.get('rooms') as FormArray;
    this._rooms.removeAt(index);
  }
  private initializeForm(): void {
    this.cottageCreationForm = this.formBuilder.group({
      cottageName: new FormControl('', [Validators.required, Validators.minLength(5)]),
      description: new FormControl('', [Validators.required, Validators.minLength(5), Validators.maxLength(511)]),
      pricePerDay: new FormControl('', [Validators.required, Validators.min(0)]),
      maxNumberOfGuests: new FormControl('', [Validators.required, Validators.min(0), Validators.max(300)]),
      address: new FormGroup({
        country: new FormControl('', [Validators.required]),
        city: new FormControl('', [Validators.required]),
        street: new FormControl('', [Validators.required]),
        houseNumber: new FormControl('', [Validators.required])
      }),
      rooms: this.formBuilder.array([this.createRooms()])
    });
  }
  // search: OperatorFunction<string, readonly string[]> = (text$: Observable<string>) =>
  //   text$.pipe(
  //     debounceTime(200),
  //     distinctUntilChanged(),
  //     map(term => term.length < 2 ? []
  //       : cities.filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1).slice(0, 10))
  //   )
}

